name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy app to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            echo ">>> Pulling latest code..."
            cd /var/www/VERICAPTURE-MAIN
            git reset --hard
            git pull origin main

            echo ">>> Setting up backend..."
            cd BACK-END
            npm install
            pm2 restart vericapture-backend || pm2 start app.js --name vericapture-backend

            echo ">>> Setting up frontend..."
            cd ../FRONT-END
            npm install

            # --- FIX vite permission ---
            chmod +x node_modules/.bin/vite
            chmod +x node_modules/esbuild/bin/esbuild || true
            chmod +x node_modules/@esbuild/linux-x64/bin/esbuild || true


            echo ">>> Building frontend..."
            npm run build

            echo ">>> Deploying frontend build..."
            sudo mkdir -p /var/www/vericapture
            sudo rm -rf /var/www/vericapture/*
            sudo cp -r dist/* /var/www/vericapture/

            echo ">>> Fixing permissions..."
            sudo chown -R www-data:www-data /var/www/vericapture
            sudo chmod -R 755 /var/www/vericapture

            echo ">>> Reloading Nginx..."
            sudo systemctl reload nginx

            echo ">>> Renewing SSL certs..."
            sudo certbot renew --quiet
            sudo systemctl reload nginx
          EOF
